name: digit_predictor
description: Aplicación predictiva de dígitos.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.9.1
  flutter_svg: ^1.1.6

  screenshot: ^1.3.0
  file_saver: ^0.1.0
  invert_colors: ^0.0.4
  image: ^3.2.0

  path_provider: ^2.0.12

  #Animate
  animate_do: ^3.0.2

  #Url open
  url_launcher: ^6.1.9

  #Permission 
  permission_handler: ^10.2.0

  #Photograpy
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3

  #Artificial Intelligence
  flutter_tflite: ^1.0.1

  #Change app name
  change_app_package_name: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/artificialIntelligence/
    - assets/Backgrounds/
    - assets/icons/
    - assets/images/
    - assets/images/social_media/
    - assets/RiveAssets/
 
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700

